version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: assetuser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: assetdb
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: assetuser
      PGPASSWORD: yourpassword
      PGDATABASE: assetdb
      PGPORT: 5432
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./media:/usr/src/app/media

volumes:
  dbdata:
